robotology/icub-models

- iCub/robots/iCubDarmstadt01/model.urdf
- iCub/robots/iCubGenova01/model.urdf
- iCub/robots/iCubGenova02/model.urdf
- iCub/robots/iCubGenova03/model.urdf
- iCub/robots/iCubGenova04/model.urdf
- iCub/robots/iCubGenova05/model.urdf
- iCub/robots/iCubLisboa01/model.urdf
- iCub/robots/iCubNancy01/model.urdf
- iCub/robots/iCubParis01/model.urdf
- iCub/robots/iCubParis02/model.urdf
Updated all models as per PR https://github.com/robotology-playground/icub-model-generator/pull/49. The updated elements in the URDF model are listed below :
- meshes filename paths
- the inertial sensors information moved from fake links to real `<sensor>` tags that are processed by **iDynTree** and respective `<gazebo>` tags processed by **Gazebo**
- Gazebo Yarp plugins definitions for the inertial sensors and the control boards.
The models **iCubGenova03**, **iCubLisboa01** and **iCubNancy01** are using DH parameters and are not generated from the CAD, so didn't get the inertial sensors updates.
The model **iCubGenova04** has extra changes:
- an additional sensor `head_mu_acc_1x1` matching the 3 1-axis accelerometers embedded in the IMU. This is required for getting the predicted …
> Updated models after icub-model-generator PR 49

- CMakeLists.txt
- README.md
If the user want to install model.config for all the files, the
`ICUB_MODELS_INSTALL_ALL_GAZEBO_MODELS` CMake option is still available.
Fix https://github.com/robotology/icub-models/issues/11
> Install model.config only for Gazebo supported models

- README.md
The issue  https://github.com/robotology-playground/icub-models/issues/7 has been closed for some time now.
> Remove outdated  reference to "work in progress" Gazebo support

- CMakeLists.txt
- feet_fixed_model.sdf.in
- fixed_model.sdf.in
Fix https://github.com/robotology/icub-models/issues/39 by generating SDF with 1.7 version if Gazebo >= 11 is found. The workaround can be removed once  https://github.com/osrf/gazebo/issues/2728 is fixed.
> Add a workaround for https://github.com/osrf/gazebo/issues/2728

- CMakeLists.txt
- iCub_manual/robots/iCubGazeboV2_5_visuomanip/model.config
- model.config.in
This PR aims to fix the use of `build tree` for the newly created manual models.
Further, I've also taken the chance to fix what I think is a bug as the SDF version wasn't correctly reported in the `model.config` files.
@traversaro @xEnVrE please have a look!
> iCub Manual Models used from build

- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_head.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_left_hand_finger.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_left_hand_index.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_left_hand_middle.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_left_hand_pinky.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_left_hand_thumb.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_right_hand_finger.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_right_hand_index.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_right_hand_middle.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_right_hand_pinky.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_right_hand_thumb.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_right_leg.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_torso.ini
This change is ignored for versions of gazebo-yarp-plugins <= 3.5.0, but for version of gazebo-yarp-plugins > 3.5.0 it aligns the behavior of the VOCAB_CM_VELOCITY control mode with the one of the real iCub robot.
This PR only handles the manually managed configuration files, while the one automatically generated will be handled by https://github.com/robotology/icub-model-generator/pull/138 .
Related issues:
* robotology/gazebo-yarp-plugins#514
* robotology/gazebo-yarp-plugins#240
> Switch controlboard plugins to set velocityControlImplementationType to integrator_and_position_pid

- AddUninstallTarget.cmake
- CMakeLists.txt
While trying to install the iCub3 model I realized that fixed models were created multiple times 
In addition, there was no ``uninstall`` target to remove them.
Apparently, due to caching, this fix works only after deleting the build folder of ``icub-models``
cc @traversaro
> Fixed multiple generation of fixed models and add uninstall target.

- fixed_model.sdf.in
This commit is required because of robotology/icub-model-generator#142
The PR fixes #58
> Fix the child link in the "fixed_base" joint for fixed_model.sdf.in

- README.md
ROS2 uses `AMENT_PREFIX_PATH`  in place of `ROS_PACKAGE_PATH`, so let's document that also this env variable needs to be set.
> Add ROS2 docs

- CHANGELOG.md
- README.md
See https://github.com/robotology/robotology-superbuild/issues/832 .
Fix https://github.com/robotology/icub-models/issues/81 .
> Fix AMENT_PREFIX_PATH  documentation

- CHANGELOG.md
- CMakeLists.txt
This requires Gazebo >= 11.
Fix https://github.com/robotology/icub-models/issues/77 .
> Use SDF 1.7 for all Gazebo models

- .github/workflows/cxx-ci.yml
- cpp/CMakeLists.txt
As https://github.com/robotology/icub-models/pull/130 adds a minimal C++ library, better to test its compilation to avoid regressions such as https://github.com/robotology/robotology-superbuild/issues/1039 .
Furthermore, add a fix for https://github.com/robotology/robotology-superbuild/issues/1039 .
> Add C++ CI workflow to GitHub Actions and fix build with Xcode's 12.4 C++ compiler

- CMakeLists.txt
The following feature introduced in https://github.com/robotology/icub-models/pull/131
https://github.com/robotology/icub-models/blob/c6948add03cacd9e84fdad74df87939efb43902c/cpp/CMakeLists.txt#L31
is available from CMake version 3.8 (see [here](https://cmake.org/cmake/help/v3.8/release/3.8.html#c-c)).
This PR to update the CMake required version accordingly.
cc @traversaro @GiulioRomualdi
> Update cmake_minimum_required to 3.8

- bindings/CMakeLists.txt
`find_package(pybind11)` depending on the pybind11 version can use old variants of `FindPython`. By calling `find_package(Python3)` first we ensure that the recommended variant `FindPython3` is used.
> Reorder python-related find_package calls

- README.md
It should not a problem to enforce this due to the limited number of methods in the C++ helper library, but it convenient to clearly state to simplify the conda-forge packaging, as in this way downstream libraries only need to be recompiled when a new major release is released.
> Document that the ABI and the API of the C++ helper library only changes at major releases

- .github/workflows/cxx-ci.yml
- CHANGELOG.md
- CMakeLists.txt
- python/CMakeLists.txt
Fix https://github.com/robotology/robotology-superbuild/issues/1076 .
Furthermore, enable the installation of Python bindings in CMake CI job to avoid these kind of regressions.
> Fix Python configuration if PYTHON_INSTDIR is a relative path

- CHANGELOG.md
- python/icub_models/icub_models.py
> Fix get_models_path() when the icub_models package is installed with the superbuild

- python/CMakeLists.txt
Now that `icub_models` is a pure Python package, we just need the interpreter.
> Do not search for Development component when searching for Python3

- CMakeLists.txt
- cpp/src/iCubModels.cpp.in
This should make the library more robust to problems in relocation in conda or similar systems, see for example:
* https://github.com/ami-iit/bipedal-locomotion-framework/pull/526
* https://github.com/conda-forge/libignition-gazebo-feedstock/issues/4
* https://github.com/conda-forge/libignition-rendering4-feedstock/issues/25
* https://github.com/conda/conda-build/issues/1674
* https://github.com/conda/conda-build/issues/2524
> Drop trailing \0 characters in value returned by iCubModels::getModelsPath function and release 1.23.4

- .github/workflows/cxx-ci.yml
- .github/workflows/pip-ci.yml
`macos-10.15` will be removed soon, see https://github.com/actions/virtual-environments/issues/5583 . 
For this reason we move CI jobs to `macos-latest`. Note that in the past for macos we used fixed release images (i.e. `macos-10.15` instead of `macos-latest`) to reduce the mantainance burden, but as these images are frequently deprecated/removed, perhaps using `-latest` should actually reduce the mantainance burden.
> Move CI jobs from soon to be removed macos-10.15 to macos-latest

- .github/workflows/cxx-ci.yml
The "Dependencies [macOS]" step was running also on Linux, and was working fine I guess because `brew` was also installed on Linux, but it started failing on 2022/09/27 probably as something in the Linux GitHub Actions image changed.
Fix https://github.com/robotology/icub-models/issues/172 .
> Do not use homebrew on Linux

- .github/workflows/cxx-ci.yml
- CHANGELOG.md
- CMakeLists.txt
Fix https://github.com/robotology/icub-models/issues/177 .
Furthermore, add tests to avoid regressions.
> Fix to make sure that ROS2 can find the iCub package

- CMakeLists.txt
- ros2/README.md
- ros2/launch/robot_state_publisher.launch.py
It depends by https://github.com/robotology/icub-models-generator/pull/228
> ROS2: add documentation for using iCubGazeboV3

- CMakeLists.txt
Fix https://github.com/robotology/icub-models/issues/189 . In https://github.com/robotology/icub-models/pull/186 there was a wrong removal of a line in the `macro(SUBDIRLIST result curdir)`.
> Fix regression in PR #186

- CHANGELOG.md
- CMakeLists.txt
- iCub_manual/package.xml
Reason to bump to v2.0.0 : 
* All the visually similar but different v1.* versions for icub-* was quite confusing to me
* Migrate to use `gazebo_yarp_robotinterface`
> Release icub-models v2.0.0

- CHANGELOG.md
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/wrappers/camera/right_camera-rgb_wrapper.xml
As per the title, this restore port names for the RGB cameras of `iCubGazeboV_2_5_visuomanip` such that they are as in 
https://github.com/robotology/icub-models/pull/45/files#diff-1e5c2f03288ab12a5b18118bc44ed0d0096511a21c7c2e02fe851c185e3de101
and not as in 
https://github.com/robotology/icub-models/pull/188/files#diff-e4397ef8e3fdcf273315c11bd778759f2352f511dbf53babc3c7b2b8284fa491
where the right camera port name was changed to `/icubSim/cam/right` by mistake.
With this change, the port names associated to the cameras are:
```console
registration name /icubSim/cam/left/depthImage:o
registration name /icubSim/cam/left/rgbImage:o
registration name /icubSim/cam/left/rpc:i
registration name /icubSim/cam/right/rgbImage:o
registration name /icubSim/cam/right/rgbImage:o/rpc
```
i.e., …
> Make iCubGazeboV_2_5_visuomanip RGB camera port names harmonized again

- .github/workflows/cxx-ci.yml
I had to cleanup the CI as there were a lot of failures related to Ubuntu 18.04 image being removed, in particular I did:
* Migrate apt CI to use Docker images, so we do not have the GitHub Actions images with the latest CMake, and instead use vanilla images for Ubuntu 20.04, Ubuntu 22.04 and Debian Sid
* Drop homebrew CI (see https://github.com/robotology/robotology-superbuild/issues/842)
See https://github.com/robotology/idyntree/pull/1063 for a similar PR.
> Migrate apt CI to use docker images and remove homebrew jobs

- CMakeLists.txt
It'd be nice to support these two robots in Gazebo.
As of now, `model.config` doesn't get installed indeed.
> Support iCubGazebo2_6 and iCubGazebo2_7

- CHANGELOG.md
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/icub_ros2.xml
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/wrappers/motorControl/alljoints-mc_nws_ros2.xml
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/wrappers/motorControl/alljoints-mc_remapper.xml
As per the title.
It adds an `icub_ros2.xml`, mimicking [that](https://github.com/robotology/robots-configuration/blob/master/iCubGenova11/icub_all_no_legs_ros2.xml) of `iCubGenova11` which, similary to `iCubGazeboV2_5_visuomanip`, does not have legs enabled.
Using this file, instead of `icub.xml`, in
https://github.com/robotology/icub-models/blob/9f5e04bbb0c119bb045db88ee333ac55d616cd92/iCub_manual/robots/iCubGazeboV2_5_visuomanip/model.urdf#L2753
a standard ROS2-based robot state publisher can be executed.
Notes:
- unfortunately, `icub_ros2.xml` cannot be made the default as it is not granted that each user of `icub-models` is also using `yarp-ros2-devices`.
- fingers and eyes are not exposed as, at the moment, the robot state publisher would not know how to extract the physical joint …
> Support joints publishing on ROS 2 for iCubGazeboV2_5_visuomanip

- CHANGELOG.md
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_left_hand_mais.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_right_hand_mais.ini
> Fix wrong port names prefix for simulated fingers hall effects sensors for iCubGazeboV2_5_visuomanip

- CMakeLists.txt
This is to ensure that https://cmake.org/cmake/help/latest/policy/CMP0094.html#policy:CMP0094 is set to `NEW`, to ensure that the Python present in the conda environment is found even if in the system another (newer) Python is found.
Fix https://github.com/robotology/icub-models/issues/216 .
Similar to https://github.com/robotology/robotology-superbuild/pull/1506 .
> Bump policy_max argument of cmake_minimum_required to 3.16

- python/CMakeLists.txt
As the code in some cases return slightly different results then the previous version (see #1238 (comment)), we only use it when Python >= 3.12 .
> Fix code to obtain Python relative install dir in Python 3.12

- CHANGELOG.md
- python/CMakeLists.txt
This is done by setting the ICUB_MODELS_PYTHON_INSTALL_DIR CMake variable.
> CMake: Permit to explictly specify Python installation directory

- CHANGELOG.md
- CMakeLists.txt
- iCub_manual/package.xml
I forgot to do this in https://github.com/robotology/icub-models/pull/221 .
> Fix version in package.xml

- README.md
- build-from-source.md
Long delayed cleanup of the README, that is now more clear. Details are provided in the following.
Cleanup installation part:
* Document conda installation, that is by far the easiest one
* For people interested in apt installation, document that robotology-superbuild is by far the easiest installation when using apt
* For users really interested in building the repo from source, move the documentation in a separate file.
* Stop documenting the usage of models from the build directory
Cleanup models part:
* Document each model installing by the repo, except the one that are in the [robots-icebox](https://github.com/robotology/robots-configuration/blob/v2.5.2/robots-icebox/README.md)
* Clearly document the `package:/`  URI required to load each model
Cleanup usage part:
* Clearly document …
> Cleanup README

- CHANGELOG.md
- CMakeLists.txt
- README.md
- iCub_manual/package.xml
Modifications for v2.5.0 release @Nicogene @martinaxgloria .
> Update changelog and README for v2.5.0 release

- CMakeLists.txt
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_left_hand_mais.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_right_hand_mais.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/icub.xml
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/icub_ros2.xml
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/wrappers/MAIS/left_arm-mais_wrapper.xml
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/wrappers/MAIS/right_arm-mais_wrapper.xml
- iCub_manual/package.xml
Fix https://github.com/robotology/icub-models/issues/234, and in particular align the simulated robot with the real robot. The chosen sensor names are `l_arm_mais` and `r_arm_mais`, as the existing names in the robot are broken (see https://github.com/robotology/robots-configuration/issues/679).
Furthermore, this migrates the mais sensor to use both `multipleanalogsensorsserver` and `gazebo_yarp_robotinterface`.
Note: this PR requires https://github.com/robotology/gazebo-yarp-plugins/pull/688 to be merged before.
> iCubGazeboV2_5_visuomanip: migrate hand encoder arrays (i.e. MAIS) sensors to use multipleanalogsensorsserver and gazebo_yarp_robotinterface

- .github/workflows/cxx-ci.yml
- .github/workflows/pip-ci.yml
- .github/workflows/pypi-ci.yml
- .github/workflows/trigger_bru.yml
- CMakeLists.txt
- iCub_manual/package.xml
- python/icub_models/icub_models.py
Instead of returning a placeholder `Path("...")` from https://github.com/robotology/icub-models/blob/468b9f7d033411dc138b877d4e229a4739ea083c/python/icub_models/icub_models.py#L32-L38 when the model name is not found I think it is more predictable and safe to raise an exception here.
> icub-models python library: Raise a `FileNotFoundError` if the model path is not found

- setup.cfg
This PR fixes a minor typo that made the Homepage URL unreachable from https://pypi.org/project/icub-models/
> Fix minor URL typo in `setup.cfg`

- CMakeLists.txt
- README.md
- iCub_manual/package.xml
- iCub_manual/ros2/README.md
As we removed iCub 3 I think it make sense to bump the major version. 
I also did a bit of follow up on https://github.com/robotology/icub-models/pull/243 . @Nicogene can you also check the `ros2` directory? It seems that it contains iCub3-related stuff, I wonder if we can remove it. It seems it was added in https://github.com/robotology/icub-models/pull/184 .
> Bump version to 3.0.0 and follow up in removal iCub3 files

- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_eyes.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_left_camera_rgbd.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_left_hand.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_right_camera_rgb.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_right_hand.ini
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/icub_gz-sim.xml
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/wrappers/camera/left_camera-rgb_wrapper_gz-sim.xml
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/wrappers/motorControl/left_arm-mc_remapper_gz-sim.xml
- iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/wrappers/motorControl/right_arm-mc_remapper_gz-sim.xml
- iCub_manual/robots/iCubGazeboV2_5_visuomanip/model.urdf
This PR adds the files for using the visuomanip model in gz-sim.
As you can see from this screenshot also the coupling of eyes and hands works fine:
It needs:
- https://github.com/robotology/gz-sim-yarp-plugins/pull/221
- https://github.com/robotology/icub-main/pull/995
- https://github.com/robotology/icub-main/pull/997
> [!warning]
> Since there is not yet a depthCamera plugin in `gz-sim-yarp-plugin`, the left camera is treated only as RGB sensor, for some 
> reason in this model it was used to be treated as depth sensor.
> Since there is not a mais sensor gz-sim plugin, the icub_gz-sim.xml does not contain the wrappers that publishes the MAIS
cc @pattacini
> iCubGazeboV2_5_visuomanip: add support for gz-sim
